### ISSUE TITLE
Uploading new media freezes

### ISSUE THREAD

**Issue by m-e-h** [felixarntz/attachment-taxonomies#1]
Whenever this plugin is active, I can't upload images or pdf.
Freezes at the point shown here.
![attach-tax](https://cloud.githubusercontent.com/assets/3585901/16810831/9bf287f2-48f3-11e6-94c9-c430e5d176f3.png)

**Comment by felixarntz** [comment]
Hi, and thanks for the report! Do you have any other plugins active? Could you please tell me which ones? I'll need some more information to investigate.

Also, when you open your browser's development tools, are there any JavaScript errors being displayed in the console?

**Comment by m-e-h** [comment]
Hey @felixarntz .
Just tried it on a clean VVV install with twentysixteen and no other plugins installed. Same issue.
I'm seeing this in the console `Uncaught TypeError: Cannot read property 'attachment_category' of undefined  VM566:91`
Let me know how else I can help.
