### ISSUE TITLE
Where to put the code example (adds an attachment taxonomy called “Location”):

### ISSUE THREAD

**Issue by denisd1** [felixarntz/attachment-taxonomies#17]
Hi,
Your plugin seems to be what I need but I just want to know where I must put your code example (adds an attachment taxonomy called “Location”) to get a third filter field.
It is not specified in the FAQ page of the plugin.

Thanks

**Comment by felixarntz** [comment]
Hi there! This GitHub repository is intended for collaboration on the plugin. For support, please open a ticket in the [support area of the plugin](https://wordpress.org/support/plugin/attachment-taxonomies).

**Comment by denisd1** [comment]
Sorry, and thank you.
