### ISSUE TITLE
Depreciated add_taxonomy ?

### ISSUE THREAD

**Issue by Uranbold** [felixarntz/attachment-taxonomies#18]
How do i correctly Load Categories and Tags from Posts.

Also how do i remove the Current Unnecessary Categories and Tags. I wanna use Cats and Tags from Post.

Thanks.

**Comment by Uranbold** [comment]
Sorry remove is OK.

But admin area there is an 1 Notice displayed.

`Notice: Attachment_Taxonomies::add_taxonomy was called with an argument that is deprecated since Attachment Taxonomies version 1.1.0 with no alternative available. in /Applications/XAMPP/xamppfiles/htdocs/ms/wp-content/plugins/attachment-taxonomies/attachment-taxonomies.php on line 313`

**Comment by felixarntz** [comment]
Apologies, the documentation on the plugin repository was outdated regarding that parameter. It is being updated with the latest release.

When calling the `add_taxonomy()` method, please omit the second parameter.
