### ISSUE TITLE
Error while attempting to upload new file.

### ISSUE THREAD

**Issue by lucymtc** [felixarntz/attachment-taxonomies#20]
Hi! I am running into a JavaScript error while attempting to upload a new file.
Error in the console:
<img width="735" alt="Screenshot 2023-10-23 at 08 21 11" src="https://github.com/felixarntz/attachment-taxonomies/assets/1204359/ba061e6c-7f5f-47c4-b6ed-6d515bec6039">

**Plugin Version** 1.2.0

**Browsers:**
Google Chrome Version 118.0.5993.88
Safari Version 16.6
Firefox Version 118.0.2

**Steps to replicate:**
- Create a new page, and add the Image block.
- Select the option to upload a new image.
- Upload an image, the error appears regardless the extension.
- Upload gets stuck at the very beginning

**Comment by lucymtc** [comment]
Hi @felixarntz, I have opened a PR to fix this error https://github.com/felixarntz/attachment-taxonomies/pull/21

**Comment by felixarntz** [comment]
@lucymtc Thank you for opening the issue and implementing a PR!

I worked through your steps to replicate, but couldn't reproduce the problem. The image uploaded just fine for me in the image block. Can you provide a bit more context? For example:
* Did you have any other plugins enabled?
* Did you have existing attachment categories or tags, or did this bug occur when there were no attachment categories or tags?
* Did you have a default attachment category set or not?

Those are just potential considerations, but really anything you can think of as potentially impactful.

**Comment by lucymtc** [comment]
Hi @felixarntz thanks for getting back.
I was able to replicate the issue on the WP instance that spins up from the contributing guidelines. 
No plugins were added, I didn't have any default category set. The error occurs only after having created some categories or tags and then try to upload the image from the Image block (with empty terms the image uploads fine).
Please let me know if you need any other information. Thanks!

**Comment by felixarntz** [comment]
@lucymtc Thanks for clarifying. I've tested this again, and I was able to replicate it. It doesn't happen immediately after the upload in the image block, it only happens when I then open the Media Library. Great catch!
