### ISSUE TITLE
[gallery] Shortcode

### ISSUE THREAD

**Issue by quasel** [felixarntz/attachment-taxonomies#8]
Hi love your clean and solid approach! 
any plans on extending the default gallery shortcode with the taxonomys like other Plugins do? 

https://developer.wordpress.org/reference/functions/gallery_shortcode/

**Comment by felixarntz** [comment]
Thanks! What exactly do you mean by extending the shortcode?

**Comment by quasel** [comment]
well something like [gallery category="slug"] for displaying the images with the taxonomys ^^
or add a new shortcode ^^  ;)

**Comment by schroeng** [comment]
Hey guys, thats exactly what i was looking for. Any plans to implement something like that?

**Comment by felixarntz** [comment]
This will be included in version 1.1.0 which I'll hopefully release a bit later today.

For reference on how to do it, see https://github.com/felixarntz/attachment-taxonomies/blob/14d4c4a8aab0faa4906ae703c498b8e4213c9009/readme.txt#L116
